In [1]:
import pickle
import pyranges as pr
import pandas as pd

In [2]:
fpath = "/nfs/turbo/umms-indikar/shared/projects/geneformer/token_dictionary.pkl"

def open_pickle(file_path):
    with open(file_path, 'rb') as file:
        loaded_object = pickle.load(file)
    return loaded_object

token_dict = open_pickle(fpath)
df = pd.DataFrame.from_dict(token_dict, orient='index')
df = df.reset_index()
df.columns = ['gene_id', 'token_id']
print(f"{df.shape=}")
df.head()

df.shape=(25426, 2)

           gene_id  token_id
0            <pad>         0
1           <mask>         1
2  ENSG00000000003         2
3  ENSG00000000005         3
4  ENSG00000000419         4

In [3]:
gtf_path = "/scratch/indikar_root/indikar1/cstansbu/HSC/references/geneTable.csv"
gtf = pd.read_csv(gtf_path)
gtf = gtf[gtf['Feature'] == 'gene']
print(f"{gtf.shape=}")
gtf.head()

/tmp/ipykernel_2403340/894331634.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  gtf = pd.read_csv(gtf_path)

gtf.shape=(61860, 26)

,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,gene_id,gene_version,...,transcript_source,transcript_biotype,tag,ccds_id,exon_number,exon_id,exon_version,protein_id,protein_version,transcript_support_level
0,1,ensembl_havana,gene,1471764,1497848,.,+,.,ENSG00000160072,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,1,havana,gene,2212522,2220738,.,+,.,ENSG00000234396,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,1,havana,gene,629061,629433,.,+,.,ENSG00000225972,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,1,havana,gene,634375,634922,.,+,.,ENSG00000198744,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,1,havana,gene,182695,184174,.,+,.,ENSG00000279928,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# merge it
df = pd.merge(df, gtf, 
              how='left',
              left_on='gene_id',
              right_on='gene_id',
             )

print(f"{df.shape=}")
outpath = "/nfs/turbo/umms-indikar/shared/projects/geneformer/token_mappings.csv"
df.to_csv(outpath, index=False)
df.head()

df.shape=(25426, 27)

,gene_id,token_id,Chromosome,Source,Feature,Start,End,Score,Strand,Frame,...,transcript_source,transcript_biotype,tag,ccds_id,exon_number,exon_id,exon_version,protein_id,protein_version,transcript_support_level
0,<pad>,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,<mask>,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENSG00000000003,2,X,ensembl_havana,gene,100627107.0,100639991.0,.,-,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ENSG00000000005,3,X,ensembl_havana,gene,100584935.0,100599885.0,.,+,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ENSG00000000419,4,20,ensembl_havana,gene,50934866.0,50959140.0,.,-,.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
gene_names = [
    
]
df